name = "Bankiffy : The Quest for Money"
author = "Austin McElwaine"
version = "26.07.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "859b4196ecd548bc9c9b51efa43bca214a52dd5bb3b886072a0e9aa05279a90d"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
