name = "Bankiffy : The Quest for Money"
author = "Austin McElwaine"
version = "26.07.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f754b37a531ec3a40c57b71f8cc05acc0a1f6f77d22606ad48c679e941678a09"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
