#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Aug 15 14:27:02 CDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=8
shaderPack=
